### PR TITLE
Minor typos

### PR DESCRIPTION
**Pull request by cgrigis**

### CODE REVIEW

**Comment by cgrigis** [comment]
Sorry, just to be sure I am not missing something here :-) Is there anything more on my side to do? What is the merge policy?

**Comment by ehoelzl** [comment]
@cgrigis Usually, for small PRs like this, the author merges it into `develop`. As for bigger changes, we need to update the the versions

**Comment by cgrigis** [comment]
@ehoelzl Understood, thank you for the explanation. I don't believe I have write access, though...

**Comment by ehoelzl** [comment]
@cgrigis Not sure if I can give you any access. But isn't the "Merge pull request" button below clickable ?

**Comment by cgrigis** [comment]
@ehoelzl Unfortunately no:
github
Hence my questions... :)

**Comment by ehoelzl** [comment]
@cgrigis I don't have the rights to add you. @Panaetius  should be able to add you

**Comment by cgrigis** [comment]
Just to be clear, I don't necessarily need write access, I am perfectly happy with someone else merging my PRs when accepted, if that fits better in the Lab's policies. :)

**Pull request merged**
