### PR TITLE
changed default gpu to k80

### PR DESCRIPTION
**Pull request by giorgiosav**
Changes default GPU type to `nvidia-tesla-k80`

### CODE REVIEW

**Comment by martinjaggi** [comment]
are you sure it's cheaper in terms of cost to accuracy?

**Comment by Panaetius** [comment]
It's 1/3 the price

**Comment by martinjaggi** [comment]
t4 ?

**Comment by giorgiosav** [comment]
We should have t4 instead of k80?

**Comment by martinjaggi** [comment]
let's look at the performance (mlbench helps :)) vs cost and you can decide base on that

**Pull request merged**
