### PR TITLE
fix torch.div RuntimeError

### PR DESCRIPTION
**Pull request by mammadhajili**
#223

### CODE REVIEW

**Comment by martinjaggi** [comment]
thanks, looks good to me! can @ehoelzl or @mmilenkoski or @Panaetius take a quick look?

(BTW after this one we should update MLbench to PyTorch 1.6, and give the automatic mixed precision a try in terms of performance impact, if anyone wants to try)

**Comment by mmilenkoski** [comment]
This change looks good to me, but we have some issue with `isort` that makes Travis checks fail. I opened #227 to address this before merging new PRs.

**Comment by mmilenkoski** [comment]
@mammadhajili can you please rebase this? I fixed the isort issue, but you need to rebase to pass the Travis check

**Comment by ehoelzl** [comment]
Closed in favor of #294

**Pull request closed without merging**
