### PR TITLE
Add aggregation by model

### LINKED ISSUE #45: Aggregate the gradients by model, instead of by layers.
It is quite a communication expensive way to aggregate the gradients layer by layer. Maybe it is better to first pack them into a big tensor, do the gradient aggregation, and then unpack the aggregated gradients.

A reference implementation can be found [here](https://github.com/epfml/LocalSGD-Code/blob/master/distributed_code/pcode/utils/tensor_buffer.py).

### PR DESCRIPTION
**Pull request by ehoelzl**
This PR adds the ability to aggregate by model instead of by layer.
The user can now specify which aggregation scheme to use (by layer or by model).

We should also add a tickbox in the GUI that would allow both modes.

Closes #45 #35  (fixes the `tox.ini` script to run black)

### CODE REVIEW

**Comment by ehoelzl** [comment]
Also, I was thinking of adding a metric to the tracker in order to monitor the time it takes to pack/unpack and time spent in communication.

What do you think ?

**Comment by martinjaggi** [comment]
about the layer vs whole model: nice, please clarify in the code/docu that it's still gradients being aggregated, not models (or say which options we support). @IamTao quick check if all ok?

about the metrics for communication time: indeed we need this, but i think @Panaetius  already had such an option, no?

**Comment by ehoelzl** [comment]
> about the layer vs whole model: nice, please clarify in the code/docu that it's still gradients being aggregated, not models (or say which options we support). 

We currently support 4 modes: by model parameters or gradients, and each of those can either be by layer or all at once. I will add accordingly in the documentation

**Comment by ehoelzl** [comment]
@IamTao I can change it to `_agg_weights_by_model`

**Pull request merged**
